version: '2'
services:
  server:
    environment:
      - 'NODE_ENV=production'
      - 'PGHOST=postgres'
      - 'PGPORT=5432'
      - 'PORT'=3000
    image: 'kollagunn/tictacktoe'
    ports:
      - '3000:3000'
      - '8080:8080'
    depends_on:
      - 'postgres'
  postgres:
    image: postgres
    environment: 
    - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
